FROM docker.io/python:3.12.0b3-slim-bullseye

RUN pip3 install flask

RUN apt update

RUN apt upgrade -y

RUN apt install git -y

RUN git clone https://github.com/ThisIsNotANamepng/buythcgfhvgchc.git fbla

RUN apt install rsync -y

WORKDIR /

ENTRYPOINT ["python3", "fbla/main.py"]
